language: node_js

node_js:
  v8.11.3
services:
  - postgresql
env:
  global:
    - CC_TEST_REPORTER_ID=6752b5321b9203b49cfe0aeec18c7bdf5bd6eb721bd05857f23dac9df77cb25a
cache:
  directories:
   - "node_modules"
addons:
    code_climate:
        repo_token: 6752b5321b9203b49cfe0aeec18c7bdf5bd6eb721bd05857f23dac9df77cb25a
script: 
  - npm test
after_success:
  - npm run coverage
  
before_script:
  - psql -c "CREATE DATABASE wmgztcls;" -U postgres
  - psql -c "CREATE USER wmgztcls WITH PASSWORD 'neHDEiBCHZh12Y9_liLe7K5-eXlTi3sS';" -U postgres
  - npm run migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  